version: 2

snapshots:
  - name: new_supply_chain_orders_scd2
    config:
      database : DBT_OUTPUT
      target_schema : SILVER_SCH
      strategy : timestamp
      unique_key : order_id
      updated_at : updated_at
      query_tag : dbt
      snapshot_meta_column_names:
        dbt_valid_from: start_date
        dbt_valid_to: end_date
        dbt_scd_id: scd_id
        dbt_updated_at: modified_date
        dbt_is_deleted: is_deleted
  - name: supply_chain_orders_snapshot_key_based_hard_delete
    config:
      target_database: DBT_OUTPUT
      target_schema: SILVER_SCH
      unique_key: order_id
      strategy: check
      check_cols: ["SUPPLIER_NAME", "PRODUCT_NAME", "QUANTITY", "UNIT_COST", "TOTAL_COST", "STATUS", "DELIVERY_DATE"]
      query_tag: dbt
      hard_deletes: new_record #by default : ignore, another type:invalidate
